### ISSUE TITLE
g15-config : ImportError: could not import gobject

### ISSUE THREAD

**Issue by netfab** [CMoH/gnome15-overlay#29]
Hi,

On a mostly stable and up-to-date system, I just noticed that I can't run g15-config anymore \:
> $ g15-config 
> Traceback (most recent call last):
>   File "/usr/bin/g15-config", line 41, in <module>
>     import gconf
> ImportError: could not import gobject (could not find _PyGObject_API object)

I'm running  the 0.10.1 version with the following useflags on \:
> alsa cairo g15 gstreamer lm_sensors

Is there anything I can do to fix the problem ? Thanks.

**Comment by CMoH** [comment]
I can confirm that. However, I cannot address it right now - no time. If anyone has a patch/idea, please contribute.

**Comment by netfab** [comment]
Just found  this topic \: http://www.evolutionlinux.com/forums/viewtopic.php?t=348
Someone has posted a patch in the first message, and below in hte topic you can find \:
> As workaround, you need downgrade python-gobject, pygobject-devel and python2-gobject to 3.12.x

Il will try this ASAP.

**Comment by netfab** [comment]
I confirm that  downgrading dev-python/pygobject from 3.14.0 from 3.12.2 (in the same slot) helps.

**Comment by CMoH** [comment]
Thank you for your research.

Since I have no idea what would be affected by downgrading pygobject on the rest of the system, I used the other idea in the link you provided to fix the import error in g15-config, which seems to work now both with versions 3.12.2 and 3.14.0 of pygobject.

I've bumped gnome15 to 0.10.2 with this fix. Please check if it works, and close the issue if you are satisfied.

**Comment by netfab** [comment]
Yes this works fine, thanks !
